phraseapp:
  access_token: 070911a66afe4f095034506feb0668579fe003f43aa6adcca1e6f1603fa7bd87
  file_format: xml
  project_id: 4f5b72ffb798b9b7556cd8271bbc111a
  pull:
    targets:
    - file: ./app/src/main/res/values-de/strings.xml
      params:
        locale_id: bdcafe58f50b780810c773599c2a7f80
    - file: ./app/src/main/res/values/strings.xml
      params:
        locale_id: f0b879f57b96c40c6683199cb9eaff27
    - file: ./app/src/main/res/values-de/strings.xml
      params:
        locale_id: bdcafe58f50b780810c773599c2a7f80
    - file: ./app/src/main/res/values/strings.xml
      params:
        locale_id: f0b879f57b96c40c6683199cb9eaff27
  push:
    sources:
    - file: ./app/src/main/res/values/strings.xml
      params:
        locale_id: f0b879f57b96c40c6683199cb9eaff27
        update_translations: true
    - file: ./app/src/main/res/values-de/strings.xml
      params:
        locale_id: bdcafe58f50b780810c773599c2a7f80
        update_translations: true
