phraseapp:
  access_token: 070911a66afe4f095034506feb0668579fe003f43aa6adcca1e6f1603fa7bd87
  file_format: xml
  project_id: 4f5b72ffb798b9b7556cd8271bbc111a
  pull:
    targets:
    - file: ./app/src/main/res/values-de/strings.xml
      params:
        locale_id: 0cb88e22a1315a4d470b0cffe322383e
    - file: ./app/src/main/res/values/strings.xml
      params:
        locale_id: 395b619157ddf44a7d153c24520ed9ec
    - file: ./app/src/main/res/values-de/strings.xml
      params:
        locale_id: 0cb88e22a1315a4d470b0cffe322383e
    - file: ./app/src/main/res/values/strings.xml
      params:
        locale_id: 395b619157ddf44a7d153c24520ed9ec
    - file: ./app/src/main/res/values-pt/strings.xml
  push:
    sources:
    - file: ./app/src/main/res/values/strings.xml
      params:
        locale_id: 395b619157ddf44a7d153c24520ed9ec
        update_translations: true
    - file: ./app/src/main/res/values-de/strings.xml
      params:
        locale_id: 0cb88e22a1315a4d470b0cffe322383e
        update_translations: true
    - file: ./app/src/main/res/values-pt/strings.xml
