phraseapp:
  access_token: 384a6eb5f97b7a014645377919afdafa020b9ce29d91273509162ae90d8e403e
  project_id: 4f5b72ffb798b9b7556cd8271bbc111a
  push:
    sources:
    - file: ./values-pt-strings.xml
      params:
        file_format: xml
  pull:
    targets:
    - file: ./values-pt/strings.xml
      params:
        file_format: xml
